---
Name: packagistbutton
---
SilverStripe\Core\Injector\Injector:
    Psr\SimpleCache\CacheInterface.PackagistShortCode:
        factory: SilverStripe\Core\Cache\CacheFactory
        constructor:
            namespace: "NewRelic"
            defaultLifetime: 86400 #Cache time in seconds
PackagistShortCode:
    UseShortHandNumbers: true #Use short hand numbers i.e 5.6K or not